[tool.poetry]
name = "CaBE"
version = "0.1.1"
description = ""
authors = ["Takuro Niitsuma <bakednt@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
bert-serving-client = "^1.10"
scikit-learn = "^0.22.1"
tensorflow = "=1.14.0"

[tool.poetry.dev-dependencies]
bert-serving-server = "^1.10"
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
